### PR TITLE
Starting PHP 8.1 the LDAP connection is an object

### PR DESCRIPTION
**Pull request by blizzz**
fixes PHP 8.1 compatibility

### CODE REVIEW

**Review by come-nc — APPROVED** [review]
Supposedly the preferred way for this migration is to use `!== false` as that covers both resource and object, and can stay this way even after resources are gone.

**Comment by come-nc** [comment]
You also have:
```
lib/LDAPConnect.php:45:  * @return bool|resource
lib/LDAPConnect.php:79:  * @return bool|resource
lib/LDAPConnect.php:102:         * @return bool|resource
```

**Comment by blizzz** [comment]
And alternatively I could check for `instanceof \LDAP\Connection` which would be most strict. Yes, would need to drop the `is_resource()` but that's not much trouble, is it.

**Comment by come-nc** [comment]
> And alternatively I could check for `instanceof \LDAP\Connection` which would be most strict. Yes, would need to drop the `is_resource()` but that's not much trouble, is it.

No, that would drop support for PHP < 8.1

**Comment by blizzz** [comment]
> > And alternatively I could check for `instanceof \LDAP\Connection` which would be most strict. Yes, would need to drop the `is_resource()` but that's not much trouble, is it.
> 
> No, that would drop support for PHP < 8.1

I mean, while keeping is_resource as long as PHP < 8.1 is supported.

**Pull request merged**
